export enum MatchPhase {
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',

  STARTING = 'STARTING',

  ROUND_START = 'ROUND_START',

  TURN_START = 'TURN_START',

  BOOSTER_SELECTION = 'BOOSTER_SELECTION',

  BOOSTER_RESOLUTION = 'BOOSTER_RESOLUTION',

  TURN_END = 'TURN_END',

  ROUND_END = 'ROUND_END',

  MATCH_END = 'MATCH_END',

  RESETTING = 'RESETTING',
}